name: On Push To Main
on:
  push:
    branches: ["main"]
jobs:
  sync-to-hf:
    name: Sync to HuggingFace Spaces
    runs-on: ubuntu-latest
    environment: hugging-face
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history to ensure proper sync
      - uses: JacobLinCool/huggingface-sync@v1
        with:
          github: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ vars.HF_SPACE_OWNER }}
          space: ${{ vars.HF_SPACE_NAME }}
          token: ${{ secrets.HF_TOKEN }}
          configuration: ".github/hf-space-config.yml"
          repository: ${{ github.repository }}  # Explicitly specify current repository
          force: true  # Force push to override existing content
          clean: true  # Clean existing files before sync
